## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("/Users/wayne/Desktop/Analysis_Project/Weather_Database/Vacation_Search/vacation_search.csv")
vacation_df.head()

City_ID             City Country  Max Temp      Current Description  \
0        0          Kavieng      PG     83.68               light rain   
1        2  Bambous Virieux      MU     70.21               light rain   
2        3        Grindavik      IS     47.89  light intensity drizzle   
3        4      Grand-Lahou      CI     77.02            broken clouds   
4        5        Jamestown      US     65.01          overcast clouds   

       Lat       Lng                             Hotel Name  
0  -2.5744  150.7967                    Nusa Island Retreat  
1 -20.3428   57.7575                         Casa Tia Villa  
2  63.8424  -22.4338  Northern Light Inn & Max's Restaurant  
3   5.1367   -5.0242         Hotel Beatitude de Grand Lahou  
4  42.0970  -79.2353         Hampton Inn & Suites Jamestown

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and </dt><dd>{Max Temp} °F</dd>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vocation_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]
# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [5]:
# 11a. Add a marker layer for each city to the map. 
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vocation_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']=='Fredericksburg')&(vacation_df['Hotel Name']=='Courtyard by Marriott Fredericksburg Historic District')]
vacation_end = vacation_df.loc[(vacation_df['City']=='Fredericksburg')&(vacation_df['Hotel Name']=='Courtyard by Marriott Fredericksburg Historic District')]
vacation_stop1 = vacation_df.loc[(vacation_df['City']=='Mayo')&(vacation_df['Hotel Name']=='Resorts Resource Group International')]
vacation_stop2 = vacation_df.loc[(vacation_df['City']=='Elizabeth City')&(vacation_df['Hotel Name']=='Hampton Inn Elizabeth City')]
vacation_stop3 = vacation_df.loc[(vacation_df['City']=='Goldsboro')&(vacation_df['Hotel Name']=='Hampton Inn Goldsboro')] 

In [8]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = pd.DataFrame(vacation_start[["Lat", "Lng"]]).to_numpy()
end = pd.DataFrame(vacation_end[["Lat", "Lng"]]).to_numpy()
stop1 = pd.DataFrame(vacation_stop1[["Lat", "Lng"]]).to_numpy()
stop2 = pd.DataFrame(vacation_stop2[["Lat", "Lng"]]).to_numpy()
stop3 = pd.DataFrame(vacation_stop3[["Lat", "Lng"]]).to_numpy()
start, stop1, stop2, stop3

(array([[ 38.3032, -77.4605]]),
 array([[ 38.8876, -76.5119]]),
 array([[ 36.2946, -76.2511]]),
 array([[ 35.3849, -77.9928]]))

In [12]:
start=(38.3032, -77.4605)
end=(38.3032, -77.4605)
stop1=(38.8876, -76.5119)
stop2=(36.2946, -76.2511)
stop3=(35.3849, -77.9928)

In [14]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
itinerary_trip_plan = gmaps.directions_layer(start,end, 
                                             waypoints=[stop1,stop2,stop3],
                                             travel_mode="DRIVING")
fig.add_layer(itinerary_trip_plan)
fig


Figure(layout=FigureLayout(height='420px'))

In [16]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

City_ID            City Country  Max Temp Current Description      Lat  \
0      678  Fredericksburg      US     76.44           clear sky  38.3032   
1      349            Mayo      US     75.29           clear sky  38.8876   
2      585  Elizabeth City      US     75.22           clear sky  36.2946   
3      501       Goldsboro      US     77.14           clear sky  35.3849   

       Lng                                         Hotel Name  
0 -77.4605  Courtyard by Marriott Fredericksburg Historic ...  
1 -76.5119               Resorts Resource Group International  
2 -76.2511                         Hampton Inn Elizabeth City  
3 -77.9928                              Hampton Inn Goldsboro

In [17]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and </dt><dd>{Max Temp} °F</dd>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [19]:
# 11a. Add a marker layer for each city to the map.
itinerary_locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(36.0, -76.0), zoom_level=5)
marker_layer = gmaps.marker_layer(itinerary_locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))